version: "3.7"

services:
  front-end:
    image: docucrypt_frontend:latest
    build:
      context: ./frontend
    entrypoint: /entrypoint.sh
    command: yarn serve
    volumes:
      - ./frontend/entrypoint.sh:/entrypoint.sh
      - ./frontend/app:/app
      - ./.env:/app/.env
    networks:
      - app_network
    ports:
      - ${FRONTEND_PORT:-8080}:8080

networks:
  app_network: